### ISSUE TITLE
panic in contour when there is a high rate of churn of IngressRoute resources

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#523]
While running performance tests for Gimbal, I noticed that Contour was crashing with an index out of range runtime error. 

I was able to reproduce the issue using the internal/e2e test framework. The test can be found here: https://github.com/alexbrand/contour/tree/rate-bug

I have seen a couple of different stack traces, but they are all index out of range inside the `route.pb.go` file from envoyproxy/go-control-plane. This is one of them:

```
panic: runtime error: index out of range

goroutine 396 [running]:
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route.encodeVarintRoute(0xc4204fe589, 0x19, 0x19, 0x19, 0x2, 0x0)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go:6207 +0x242
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route.(*WeightedCluster).MarshalTo(0xc4203cd710, 0xc4204fe589, 0x19, 0x19, 0x1c, 0x2, 0x1)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go:4873 +0x2e5
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route.(*RouteAction_WeightedClusters).MarshalTo(0xc4201c3eb8, 0xc4204fe587, 0x1b, 0x1b, 0x153a1d7, 0x1c, 0x1)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go:5349 +0xe1
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route.(*RouteAction).MarshalTo(0xc4204b6ff0, 0xc4204fe587, 0x1b, 0x1b, 0x1e, 0x2, 0xc4204a9468)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go:5152 +0x1326
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route.(*Route_Route).MarshalTo(0xc4201c3eb0, 0xc4204fe585, 0x1d, 0x1d, 0x3, 0x0, 0x0)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go:4801 +0xe1
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route.(*Route).MarshalTo(0xc4204a9578, 0xc4204fe580, 0x22, 0x22, 0x25, 0x35, 0x1)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go:4756 +0x164
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route.(*VirtualHost).MarshalTo(0xc4204a9710, 0xc4204fe54b, 0x57, 0x57, 0x5a, 0x454b, 0x0)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/route/route.pb.go:4634 +0x33a
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2.(*RouteConfiguration).MarshalTo(0xc420406000, 0xc4204fa000, 0x45a2, 0x45a2, 0x45a2, 0x45a2, 0x1bc77c0)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/rds.pb.go:368 +0x1dc
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2.(*RouteConfiguration).Marshal(0xc420406000, 0x1cfa860, 0xc420406000, 0x58000e0, 0xc420406000, 0x1)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/rds.pb.go:345 +0x7f
github.com/heptio/contour/vendor/github.com/gogo/protobuf/proto.Marshal(0x1cfa860, 0xc420406000, 0x2, 0xc4201c0a50, 0x2, 0x2, 0x2)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/gogo/protobuf/proto/encode.go:233 +0x115
github.com/heptio/contour/internal/grpc.toAny(0x1cfa460, 0xc42021fd30, 0x1c869d0, 0x1c869d0, 0xc420518108, 0xc420520a50, 0x0, 0x0)
	/Users/abrand/go/src/github.com/heptio/contour/internal/grpc/xds.go:145 +0xe8
github.com/heptio/contour/internal/grpc.(*xdsHandler).stream(0xc4201a7f60, 0x5800000, 0xc42021e030, 0x0, 0x0)
	/Users/abrand/go/src/github.com/heptio/contour/internal/grpc/xds.go:115 +0x666
github.com/heptio/contour/internal/grpc.(*grpcServer).StreamRoutes(0xc4201a7f60, 0x1d0ca00, 0xc42021e030, 0x1cf36e0, 0xc4201a7f60)
	/Users/abrand/go/src/github.com/heptio/contour/internal/grpc/server.go:117 +0x6a
github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2._RouteDiscoveryService_StreamRoutes_Handler(0x1bf40e0, 0xc4201a7f60, 0x1d09d00, 0xc420298140, 0x235daf0, 0x10)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/rds.pb.go:279 +0xb2
github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420292000, 0x1d0c100, 0xc4200aac00, 0xc4205df900, 0xc420284570, 0x232b860, 0x0, 0x0, 0x0)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:1052 +0x9b4
github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420292000, 0x1d0c100, 0xc4200aac00, 0xc4205df900, 0x0)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:1146 +0x12b1
github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42036c020, 0xc420292000, 0x1d0c100, 0xc4200aac00, 0xc4205df900)
	/Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:635 +0xa1
FAIL	github.com/heptio/contour/internal/e2e	0.130s
```

**Comment by alexbrand** [comment]
I ran the test with the race detector enabled. We have a data race in resources.go, when we are sorting  the resources. This is one of the data races detected:

```
==================
WARNING: DATA RACE
Read at 0x00c4204bb5d0 by goroutine 87:
  github.com/heptio/contour/internal/grpc.(*virtualHostsByName).Less()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/resources.go:139 +0x8f
  sort.insertionSort()
      /usr/local/Cellar/go/1.10.3/libexec/src/sort/sort.go:27 +0xa9
  sort.stable()
      /usr/local/Cellar/go/1.10.3/libexec/src/sort/sort.go:364 +0x5e
  sort.Stable()
      /usr/local/Cellar/go/1.10.3/libexec/src/sort/sort.go:357 +0x60
  github.com/heptio/contour/internal/grpc.(*RDS).Values()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/resources.go:120 +0x140
  github.com/heptio/contour/internal/grpc.toAny()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/xds.go:142 +0x66
  github.com/heptio/contour/internal/grpc.(*xdsHandler).stream()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/xds.go:115 +0x75b
  github.com/heptio/contour/internal/grpc.(*grpcServer).StreamRoutes()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/server.go:117 +0x7b
  github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2._RouteDiscoveryService_StreamRoutes_Handler()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/rds.pb.go:279 +0xd2
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:1052 +0x1298
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).handleStream()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:1146 +0x12f8
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:637 +0xac

Previous write at 0x00c4204bb5d0 by goroutine 85:
  github.com/heptio/contour/internal/grpc.(*virtualHostsByName).Swap()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/resources.go:138 +0x167
  sort.insertionSort()
      /usr/local/Cellar/go/1.10.3/libexec/src/sort/sort.go:28 +0x64
  sort.stable()
      /usr/local/Cellar/go/1.10.3/libexec/src/sort/sort.go:364 +0x5e
  sort.Stable()
      /usr/local/Cellar/go/1.10.3/libexec/src/sort/sort.go:357 +0x60
  github.com/heptio/contour/internal/grpc.(*RDS).Values()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/resources.go:120 +0x140
  github.com/heptio/contour/internal/grpc.toAny()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/xds.go:142 +0x66
  github.com/heptio/contour/internal/grpc.(*xdsHandler).stream()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/xds.go:115 +0x75b
  github.com/heptio/contour/internal/grpc.(*grpcServer).StreamRoutes()
      /Users/abrand/go/src/github.com/heptio/contour/internal/grpc/server.go:117 +0x7b
  github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2._RouteDiscoveryService_StreamRoutes_Handler()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/rds.pb.go:279 +0xd2
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:1052 +0x1298
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).handleStream()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:1146 +0x12f8
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:637 +0xac

Goroutine 87 (running) created at:
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:635 +0xb8
  github.com/heptio/contour/vendor/google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/transport/http2_server.go:387 +0x1416
  github.com/heptio/contour/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/transport/http2_server.go:419 +0x648
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:633 +0x16e
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).handleRawConn.func2()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:590 +0x53
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).handleRawConn.func3()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:598 +0x34

Goroutine 85 (running) created at:
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:635 +0xb8
  github.com/heptio/contour/vendor/google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/transport/http2_server.go:387 +0x1416
  github.com/heptio/contour/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/transport/http2_server.go:419 +0x648
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:633 +0x16e
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).handleRawConn.func2()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:590 +0x53
  github.com/heptio/contour/vendor/google.golang.org/grpc.(*Server).handleRawConn.func3()
      /Users/abrand/go/src/github.com/heptio/contour/vendor/google.golang.org/grpc/server.go:598 +0x34
==================
```

**Comment by davecheney** [comment]
Good find. Let’s add -race tests to make check as part of CI. 

Another idea might be to build :master images with -race so we can catch this stuff during development.

**Comment by davecheney** [comment]
Thanks for the repro case, i've got a fix coming today.
